services:
  - type: static
    name: dept-system-frontend
    rootDir: frontend
    buildCommand: ""
    publishDir: "."

  - type: web
    name: dept-system-backend
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
